server:
  port: 80
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.host}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        open-in-view : false
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: info
