

# 테스트 설정 yml

server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: ${rds.url}
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        open-in-view : false
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
