server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
#url: jdbc:mysql://localhost:3306/mysql
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        open-in-view: false
        default_batch_fetch_size: 100
        format_sql: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

cloud:
  aws:
    s3:
      bucket: findbugs-bukkit
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
    stack:
      auto: false